### ISSUE TITLE
"demand some taxes back"

### ISSUE THREAD

**Issue by dfvalue** [skymatic/reverse-charger#16]
"if you are a company/developer from the EU, you can also demand some taxes back you paid twice" (from your README)

Could you elaborate what you mean by that? What taxes can be demanded back?

Thanks

**Comment by overheadhunter** [comment]
By noting on the invoice that Apple/Google are responsible for paying VAT (which they are and what they do for you - you don't have a choice), you can prove to your tax office that the VAT is already taken care of.

Some countries (basically EU plus a few others) agree that the same transaction must not be taxed twice. In the case of digital consumer products this is the country of the consumer (i.e. where your app was sold). In this case the VAT doesn't need to be payed in the country of the app developer again. So the payouts you get from Apple/Google can be treated as net revenues.

**Comment by tobihagemann** [comment]
I have updated the README to remove the sentence you quoted. It's not true that you can "demand" anything "back". This whole project only exists so that you can make your tax statement in the EU.

I've changed the sentence to:

> Additionally, if you are a company/developer from the EU, it would be wrong to declare the whole sum of your revenue, because you have to explicitly separate EU and non-EU sales in your tax statement.

In our specific case, we were able to "demand" something back, because our tax accountant made a mistake and declared the payouts from Apple/Google as gross revenue instead of net revenue.

**Comment by tobihagemann** [comment]
Just wanted to add: This is **not** legal advice. If you are unsure, please consult a lawyer or tax advisor. We are just stating our experience.
